<?php
/**
 * @License(name="GNU General Public License", version="3.0")
 *
 * Copyright (C) 2010 Tom Kaczocha <freedomdeveloper@yahoo.com>
 *
 * This file is part of LaMantengo.
 *
 * LaMantengo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LaMantengo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LaMantengo.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
// link.php
$title_home = "Home";

$error_insert_link = "Error trying to insert link. Please retry later. If problem persists, consider informing site's administrator.";

$instructions = 'Enter link\'s destination in the text box above. Read the Terms of Service and accept them. Click "Link" button and the site will give you back a new link, whose destination could be modified by any visitor. By registering, your links could be modified only by your account.';

$link_button = "Link";

// reging.php
$login_button = "Login";

$username = "Username";

$password = "Password";

$login_to_site = "Login to Site";

$register = "Register";

$register_title = "Register a new User Account";

$forgot_password = "I forgot my password";

$forgot_password_title = "Recover Password";

// footer.php
$terms_of_service_link = "Terms of Service";

$terms_of_service_link_title = "Read the Terms of Service";

$send_site_query_title_tom = "Send Site Query";

$idea_and_realisation = "Idea and Realization: UnWebMaster.Com.Ar";
*/

$en_message_ar = array();

// link.php
$en_message_ar['en']['title_home']                      = "Home";
$en_message_ar['en']['error_insert_link']               = "Error trying to insert link. Please retry later. If problem persists, consider informing site's administrator.";
$en_message_ar['en']['instructions']                    = 'Enter link\'s destination in the text box above. Read the Terms of Service and accept them. Click "Link" button and the site will give you back a new link, whose destination could be modified by any visitor. By registering, your links could be modified only by your account.';
// reging.php
$en_message_ar['en']['link_button']                     = "Link";
$en_message_ar['en']['login_button']                    = "Login";
$en_message_ar['en']['username']                        = "Username";
$en_message_ar['en']['password']                        = "Password";
$en_message_ar['en']['login_to_site']                   = "Login to Site";
$en_message_ar['en']['register']                        = "Register";
$en_message_ar['en']['register_title']                  = "Register a new User Account";
$en_message_ar['en']['forgot_password']                 = "I forgot my password";
$en_message_ar['en']['forgot_password_title']           = "Recover Password";
// footer.php
$en_message_ar['en']['terms_of_service_link']           = "Terms of Service";
$en_message_ar['en']['terms_of_service_link_title']     = "Read the Terms of Service";
$en_message_ar['en']['send_site_query_title_tom']       = "Send Site Query";
$en_message_ar['en']['idea_and_realisation']            = "Idea and Realization: UnWebMaster.Com.Ar";

?>