<?php

/**
 * @License(name="GNU General Public License", version="3.0")
 * 
 * Copyright (C) 2010 Tom Kaczocha <freedomdeveloper@yahoo.com>
 *
 * This file is part of LaMantengo.
 *
 * LaMantengo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LaMantengo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LaMantengo.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
// link.php
$title_home = "Inicio";

$error_insert_link = "Error al agregar el link a la base de datos. Por favor, intente m&aacute;s tarde. Si el problema persiste, considere informar al WebMaster.<br />\n";

$instructions = 'Ingrese el destino al que quiere linkear en la caja de texto de arriba. Lea las Condiciones del Servicio y acéptelas.
                Clickee el botón "Linkear" y el sitio le devolverá un nuevo enlace, cuyo destino podrá ser modificado por cualquier visitante.
                Registrándose, los links que cree podrán ser modificados por su cuenta de usuario únicamente.';

$link_button = "Linkear";

// reging.php

$login_button = "Entrar";

$username = "Nombre de usuario";

$password = "Contrase&ntilde;a de usuario";

$login_to_site = "Ingresar al sitio";

$register = "Registrarse";

$register_title = "Registrar una nueva cuenta de usuario";

$forgot_password = "Olvid&eacute; mi password";

$forgot_password_title = "Recuperar contrase&ntilde;a de usuario";

$terms_of_service_link = "Condiciones del servicio";

$terms_of_service_link_title = "Leer las Condiciones del servicio";

$send_site_query_title_tom = "Envío de consulta de la web";

$idea_and_realisation = "Idea y realizaci&oacute;n: UnWebMaster.Com.Ar";
*/

$es_message_ar = array();

// link.php
$es_message_ar['es']['title_home']                      = "Inicio";
$es_message_ar['es']['error_insert_link']               = 'Ingrese el destino al que quiere linkear en la caja de texto de arriba. Lea las Condiciones del Servicio y acéptelas.
                                                           Clickee el botón "Linkear" y el sitio le devolverá un nuevo enlace, cuyo destino podrá ser modificado por cualquier visitante.
                                                           Registrándose, los links que cree podrán ser modificados por su cuenta de usuario únicamente.';
$es_message_ar['es']['instructions']                    = 'Enter link\'s destination in the text box above. Read the Terms of Service and accept them. Click "Link" button and the site will give you back a new link, whose destination could be modified by any visitor. By registering, your links could be modified only by your account.';
// reging.php
$es_message_ar['es']['link_button']                     = "Linkear";
$es_message_ar['es']['login_button']                    = "Entrar";
$es_message_ar['es']['username']                        = "Nombre de usuario";
$es_message_ar['es']['password']                        = "Contrase&ntilde;a de usuario";
$es_message_ar['es']['login_to_site']                   = "Ingresar al sitio";
$es_message_ar['es']['register']                        = "Registrarse";
$es_message_ar['es']['register_title']                  = "Registrar una nueva cuenta de usuario";
$es_message_ar['es']['forgot_password']                 = "Olvid&eacute; mi password";
$es_message_ar['es']['forgot_password_title']           = "Recuperar contrase&ntilde;a de usuario";
// footer.php
$es_message_ar['es']['terms_of_service_link']           = "Condiciones del servicio";
$es_message_ar['es']['terms_of_service_link_title']     = "Leer las Condiciones del servicio";
$es_message_ar['es']['send_site_query_title_tom']       = "Envío de consulta de la web";
$es_message_ar['es']['idea_and_realisation']            = "Idea y realizaci&oacute;n: UnWebMaster.Com.Ar";


?>
