<?php

/**
 * @License(name="GNU General Public License", version="3.0")
 * 
 * Copyright (C) 2010 Tom Kaczocha <freedomdeveloper@yahoo.com>
 *
 * This file is part of LaMantengo.
 *
 * LaMantengo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LaMantengo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LaMantengo.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
// link.php
$title_home = "Inicio";

$error_insert_link = "Error al agregar el link a la base de datos. Por favor, intente m&aacute;s tarde. Si el problema persiste, considere informar al WebMaster.<br />\n";

$instructions = 'Ingrese el destino al que quiere linkear en la caja de texto de arriba. Lea las Condiciones del Servicio y acéptelas.
                Clickee el botón "Linkear" y el sitio le devolverá un nuevo enlace, cuyo destino podrá ser modificado por cualquier visitante.
                Registrándose, los links que cree podrán ser modificados por su cuenta de usuario únicamente.';

$link_button = "Linkear";

// reging.php

$login_button = "Entrar";

$username = "Nombre de usuario";

$password = "Contrase&ntilde;a de usuario";

$login_to_site = "Ingresar al sitio";

$register = "Registrarse";

$register_title = "Registrar una nueva cuenta de usuario";

$forgot_password = "Olvid&eacute; mi password";

$forgot_password_title = "Recuperar contrase&ntilde;a de usuario";

$terms_of_service_link = "Condiciones del servicio";

$terms_of_service_link_title = "Leer las Condiciones del servicio";

$send_site_query_title_tom = "Envío de consulta de la web";

$idea_and_realisation = "Idea y realizaci&oacute;n: UnWebMaster.Com.Ar";
*/

$es_message_ar = array();

// link.php
$es_message_ar['es']['title_home']                      = "Inicio";
$es_message_ar['es']['error_insert_link']               = "Error al agregar el link a la base de datos. Por favor, intente m&aacute;s tarde. Si el problema persiste, considere informar al WebMaster.<br />\n";
$es_message_ar['es']['instructions']                    = 'Ingrese el destino al que quiere linkear en la caja de texto de arriba. Lea las Condiciones del Servicio y acéptelas.
                                                           Clickee el botón "Linkear" y el sitio le devolverá un nuevo enlace, cuyo destino podrá ser modificado por cualquier visitante.
                                                           Registrándose, los links que cree podrán ser modificados por su cuenta de usuario únicamente.';
$es_message_ar['es']['error_url']                       = "La direcci&oacute;n que intenta visitar es err&oacute;nea (no incluye el id del link). Por favor, verif&iacute;quela.<br />\n";
$es_message_ar['es']['unknown_url']                     = "El link que intenta visitar no existe o fue dado de baja en nuestro sitio.<br />\n";

// reging.php
$es_message_ar['es']['link_button']                     = "Linkear";
$es_message_ar['es']['login_button']                    = "Entrar";
$es_message_ar['es']['username']                        = "Nombre de usuario";
$es_message_ar['es']['password']                        = "Contrase&ntilde;a de usuario";
$es_message_ar['es']['login_to_site']                   = "Ingresar al sitio";
$es_message_ar['es']['register']                        = "Registrarse";
$es_message_ar['es']['register_title']                  = "Registrar una nueva cuenta de usuario";
$es_message_ar['es']['forgot_password']                 = "Olvid&eacute; mi password";
$es_message_ar['es']['forgot_password_title']           = "Recuperar contrase&ntilde;a de usuario";

$es_message_ar['es']['title_profile']                   = "Perfil de usuario";
$es_message_ar['es']['profile_link']                    = "Perfil";
$es_message_ar['es']['title_links']                     = "Ver todos los links del usuario";
$es_message_ar['es']['links_link']                      = "Mis Links";
$es_message_ar['es']['title_sess_close']                = "Cerrar la sesi&oacute;n actual";
$es_message_ar['es']['sess_close_link']                 = "Salir";

// footer.php
$es_message_ar['es']['terms_of_service_link']           = "Condiciones del servicio";
$es_message_ar['es']['terms_of_service_link_title']     = "Leer las Condiciones del servicio";
$es_message_ar['es']['send_site_query_title_tom']       = "Envío de consulta de la web";
$es_message_ar['es']['idea_and_realisation']            = "Idea y realizaci&oacute;n: UnWebMaster.Com.Ar";

// register.php
$es_message_ar['es']['title_register']                  = "Registrar cuenta";
$es_message_ar['es']['error_agree']                     = "You must accept the Terms of Service to register.<br />\n";
$es_message_ar['es']['error_username']                  = "El nombre de usuario est&aacute; vac&iacute;o.<br />\n";
$es_message_ar['es']['error_size']                      = "El nombre de usuario debe tener 4 caracteres como m&iacute;nimo.<br />\n";
$es_message_ar['es']['error_email_empty']               = "El e-mail est&aacute; vac&iacute;o.<br />\n";
$es_message_ar['es']['error_email_nomatch']             = "Los e-mail no coinciden.<br />\n";
$es_message_ar['es']['error_email_invalid']             = "El e-mail ingresado es inv&aacute;lido.<br />\n";
$es_message_ar['es']['error_already_registered']        = "El nombre de usuario o cuenta de e-mail ingresados ya se encuentran registrados.<br />\n";
$es_message_ar['es']['error_already_reg']               = "Ya est&aacute; loggeado, por lo que no puede volver a registrarse.<br />\n";

$es_message_ar['es']['registered_successfully']         = "Su cuenta ha sido creada exitosamente. Revise su e-mail (<b>$email</b>) para obtener sus datos de ingreso.<br />\n";
$es_message_ar['es']['important_message']               = "<br /><br /><b>** IMPORTANTE **:</b> Est&aacute;s viendo este mensaje porque el sitio est&aacute; en beta. Probablemente tu cuenta sea eliminada luego de unos d&iacute;as, o se actualizar&aacute; tu password para verificar tu email.<br />\n";

$es_message_ar['es']['username_message']                = "(m&iacute;nimo 4 caracteres)";
$es_message_ar['es']['first_name_message']              = "(para usar en caso de contacto)";
$es_message_ar['es']['first_name_label']                = "Nombre:";
$es_message_ar['es']['email_message']                   = "(v&aacute;lido - se enviar&aacute; la contrase&ntilde;a))";
$es_message_ar['es']['email_repeat_label']              = "Repite Email*:";
$es_message_ar['es']['email_repeat_message']            = "(repite la direcci&oacute;n)";

$es_message_ar['es']['title_agreeToS']                  = "Acepto los ToS";
$es_message_ar['es']['title_read_ToS']                  = "Leer los ToS";
$es_message_ar['es']['accept_agree_label']              = "Acepto los";
$es_message_ar['es']['register_button']                 = "Registrarse";
$es_message_ar['es']['reset_button']                    = "Limpiar";

$es_message_ar['es']['reg_instruct']                    = "Ingrese el nombre de usuario con el que quiere registrarse en el sitio, su nombre real (opcional, solamente figurar&aacute; cuando debamos contactarnos con usted), y un e-mail v&aacute;lido.<br />
                                                           Adem&aacute;s, ingrese las dos palabras que ve en la imagen, para verificar que usted es un humano, y no una computadora haciendo registros autom&aacute;ticos.<br />
                                                           Se enviar&aacute; un mensaje a esa direcci&oacute;n indicando sus datos de inicio de sesi&oacute;n, y ser&aacute; la direcci&oacute;n de contacto asociada a su cuenta.<br />
                                                           Para registrarse en el sitio tiene que estar de acuerdo con nuestros <a href=\"tos.php?sid=$sid\" target=\"_blank\"";

$es_message_ar['es']['read_ToS_nWindow']                = "Leer los ToS (en una ventana nueva)";

// email_register.php
$es_message_ar['es']['mail_subj']                       = "Registro en LaMantengo.Com.Ar";
$es_message_ar['es']['mail_line1']                      = "Bienvenid@ a LaMantengo.Com.Ar<br />\r\n";
$es_message_ar['es']['mail_line2']                      = "Para comenzar a usar el servicio, inicia sesi&oacute;n en <a href=\"http://www.lamantengo.com.ar/login.php\">http://www.lamantengo.com.ar/login.php</a>.<br />\r\n";
$es_message_ar['es']['mail_line3']                      = "Tus datos de login son:<br />\r\n";
$es_message_ar['es']['mail_username']                   = "Username: <b>$username</b><br />\r\n";
$es_message_ar['es']['mail_password']                   = "Contrase&ntilde;a: <b>$password</b><br />\r\n";
$es_message_ar['es']['mail_line4']                      = "Podr&aacute; cambiar su contrase&ntilde;a desde su perfil, luego de iniciar sesi&oacute;n.<br />\r\n";
$es_message_ar['es']['mail_line5']                      = "En caso de olvidar su contrase&ntilde;a, si bien no es posible recuperarla, podr&aacute; generar una nueva ingresando a <a href=\"http://www.lamantengo.com.ar/forgot.php\">http://www.lamantengo.com.ar/forgot.php</a><br />\r\n";



?>
